---
- name: Copy Cisco IOS image from TFTP to 3560-CX
  hosts: cisco_switch
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  vars:
    tftp_server: 10.0.0.82
#    image_subdir: /private/tftpboot/
    image_filename: c3560cx-universalk9-mz.152-7.E12.bin
#    tftp_path: "tftp://{{ tftp_server}}/{{ image_filename }}"
    destination_path: flash:{{ image_filename }}
    expected_md5: "39e232a6309e460f4d9eba9ca090031c"  # Replace with actual MD5

  tasks:

    - name: Verify TFTP server reachability
      ios_command:
        commands:
          - ping {{ tftp_server }}
      register: ping_result

    - name: Show ping result
      debug:
        var: ping_result.stdout_lines

    - name: Copy image from TFTP to flash
      ios_command:
        commands:
          - copy tftp://{{ tftp_server }}/{{ image_filename }} {{ destination_path }}
      vars:
        ansible_command_timeout: 600  # Increaseed to 10 min

    - name: Verify image copied
      ios_command:
        commands:
          - dir flash:
      register: flash_contents

    - name: Confirm image is present
      fail:
        msg: "Image not found in flash after copy."
      when: image_filename not in flash_contents.stdout[0]

    - name: Verify MD5 checksum of copied image
      ios_command:
        commands:
          - verify /md5 {{ destination_path }}
      register: md5_result

    - name: Check MD5 hash matches expected
      fail:
        msg: "MD5 checksum mismatch! Expected {{ expected_md5 }}, got {{ md5_result.stdout[0].split()[-1] }}"
      when: md5_result.stdout[0].split()[-1] != expected_md5

    - name: Set boot variable to new image
      ios_config:
        lines:
          - boot system switch all {{ destination_path }}

    - name: Save configuration
      ios_command:
        commands:
          - write memory

#    - name: Wait 10 seconds before reload
#  pause:
#    seconds: 10
        
    - name: Prompt for reload confirmation
      pause:
        prompt: "Image copied and verified. Press Enter to reload the switch or Ctrl+C to cancel."

    - name: Reload the switch
      ios_command:
        commands:
          - reload
      vars:
        ansible_command_timeout: 60


